apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-postgres
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres
  template:
    metadata:
      labels:
        app: order-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              value: orderuser
            - name: POSTGRES_PASSWORD
              value: orderpass
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata   # ← important
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: order-postgres
  namespace: orders
spec:
  selector:
    app: order-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

# ======================
# Redis
# ======================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-redis
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-redis
  template:
    metadata:
      labels:
        app: order-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-redis
  namespace: orders
spec:
  selector:
    app: order-redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP