replicaCount: 3

image:
  repository: asia-south1-docker.pkg.dev/order-service-gke-demo/order-service/order-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 300m
    memory: 640Mi
  limits:
    cpu: 900m
    memory: 1280Mi

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/orders
  SPRING_DATA_REDIS_HOST: order-redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_CACHE_TYPE: redis

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 40
  periodSeconds: 8
  timeoutSeconds: 3
  failureThreshold: 3

ingress:
  enabled: true