{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "order-service.fullname" . }}-dumps
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dumps.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "order-service.fullname" . }}-logs
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }}
